# Generated by Django 5.2.14 on 2026-06-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('eom', 'Employee of the Month'), ('anniversary', 'Work Anniversary'), ('welcome', 'Welcome'), ('custom', 'Custom')], max_length=32)),
                ('source_image', models.ImageField(upload_to='card-templates/')),
                ('placeholder_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='companies.company')),
            ],
        ),
    ]
