# Generated by Django 5.2.14 on 2026-06-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company-logos/')),
                ('brand_color', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
